[package]
name = "std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
good_memory_allocator = "0.1.7"
spin = "0.9"
vmem = { git = "https://github.com/archaic-archea/vmem.git" }